# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a469468a1a82d2915ed3bb4e6731b6f327dd9072fc467a68ce0414bef14aab6ff5aabff3e531833a6755478b1b495e39e1cc0acfffc4f497ddffe9c37f64cba

test:
  secret_key_base: 40975f08ea8a7f2e08629b5188b970bc44ad6f557f65dbd2f47d41f22496e22ee67dbc06379435ec6218a75b7c5a7110e3b638343d051287cfa21947ea52792b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
